### ISSUE TITLE
使用ConstraintLayout出现 java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.support.constraint.ConstraintLayout$LayoutParams

### ISSUE THREAD

**Issue by hacket** [luckybilly/Gloading#13]
将demo中的`activity_wrap_single_view.xml`改成ConstraintLayout，Crash了：
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent" android:layout_height="match_parent"
        android:id="@+id/root"
        android:background="@color/main_bg"
        android:padding="10dp">

    <ImageView
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            android:background="#44ff0000"
            android:id="@+id/content_view"
            android:visibility="visible"
            android:layout_width="300dp"
            android:layout_height="300dp"
    />

    <TextView
        android:text="@string/wrap_single_view"
        android:textColor="@android:color/white"
        android:textSize="16sp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_goneMarginTop="30dp"
        app:layout_constraintTop_toBottomOf="@+id/content_view"
        />

</android.support.constraint.ConstraintLayout>
```
出错的情况是，你要wrap的view会被其他的view引用，不引用的话不会出错。
```
 java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.support.constraint.ConstraintLayout$LayoutParams
        at android.support.constraint.ConstraintLayout.getTargetWidget(ConstraintLayout.java:1144)
        at android.support.constraint.ConstraintLayout.setChildrenConstraints(ConstraintLayout.java:1028)
        at android.support.constraint.ConstraintLayout.updateHierarchy(ConstraintLayout.java:803)
        at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:1561)
        at android.view.View.measure(View.java:23196)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23196)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:461)
        at android.view.View.measure(View.java:23196)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:720)
        at android.view.View.measure(View.java:23196)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2764)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1617)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1901)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1505)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7352)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1062)
        at android.view.Choreographer.doCallbacks(Choreographer.java:874)
        at android.view.Choreographer.doFrame(Choreographer.java:805)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1048)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6814)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by hacket** [comment]
对上面的ImageView包裹一层FrameLayout就可以了

**Comment by luckybilly** [comment]
目前还没想到更优雅的办法，欢迎大家提交PR

**Comment by stfnt** [comment]
hello，我添加了当view的父布局是ConstraintLayout，反射添加ConstraintLayout布局的处理，测试没问题，https://github.com/luckybilly/Gloading/pull/26

**Comment by luckybilly** [comment]
v1.1.0版已支持ConstraintLayout， [commit](https://github.com/luckybilly/Gloading/commit/0fb78cec9a13c71c13716d9c0e793f1dbe2d5a59)

Thanks @stfnt

**Comment by saljith** [comment]
update constraint layout library to latest
  implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
