### ISSUE TITLE
Dome 中GridView运行报错

### ISSUE THREAD

**Issue by lxn1445663013** [luckybilly/Gloading#7]
04-11 09:36:48.722 1487-1487/com.billy.android.loadingstatusview E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.billy.android.loadingstatusview, PID: 1487
    java.lang.ClassCastException: android.view.ViewGroup$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
        at android.widget.GridView.onMeasure(GridView.java:1046)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:327)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1940)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1137)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1319)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1024)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5694)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
        at android.view.Choreographer.doFrame(Choreographer.java:544)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by luckybilly** [comment]
你是下载demo apk运行还是clone代码自己编译运行的呢？
我刚试了下都是OK的，你有没有改过代码呢？如果改了代码或者实际应用请注意以下几点：

1. 从实现原理可以看出，为View添加加载状态的时候，Gloading会创建一个FrameLayout，将目标View和自身放入此FrameLayout，从而实现完整覆盖目标View的效果，所以**应当使用holder.getWrapper()作为GridView的contentView，参考[demo](https://github.com/luckybilly/Gloading/blob/87a71d3e724adf0905489c69f975381c1dfcc961/app/src/main/java/com/billy/android/loadingstatusview/wrapview/WrapGridViewItemActivity.java#L92)代码(注意看注释)**
```java

@Override
public View getView(int position, View convertView, ViewGroup parent) {
    ViewHolder viewHolder;
    if (convertView == null) {
        ImageView imageView = new ImageView(parent.getContext());
        imageView.setLayoutParams(new ViewGroup.LayoutParams(size, size));
        Gloading.Holder holder = Gloading.getDefault().wrap(imageView);
        viewHolder = new ViewHolder(holder, imageView);
        //use wrapper view instead of origin imageView
        convertView = holder.getWrapper();
        convertView.setTag(viewHolder);
    } else {
        viewHolder = (ViewHolder) convertView.getTag();
    }
    viewHolder.showImage(list.get(position));
    return convertView;
}
```

2. 除了GridView（及所有AdapterView的子类）之外，RecyclerView也一样，ViewHolder中调用`super(holder.getWrapper())` 替代`super(view)`，[demo代码](https://github.com/luckybilly/Gloading/blob/87a71d3e724adf0905489c69f975381c1dfcc961/app/src/main/java/com/billy/android/loadingstatusview/wrapview/WrapRecyclerViewItemActivity.java#L105)
3. 另外，像[SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout/)这样的三方库，由于会持有第一次添加进去的子View，所以如果要一起使用的话，应当这样添加：`refreshLayout.addView(holder.getWrapper, layoutParams)`

**Comment by lxn1445663013** [comment]
我是克隆代码自己运行的，刚刚我下载Dome试了也是报错，然后根据你上面提示的我比对了一下代码，好像克隆下来的代码里面缺少了那一行
  class ViewHolder implements Runnable {
            private final Gloading.Holder holder;
            ImageView imageView;
            private String curUrl;

            ViewHolder(Gloading.Holder holder, ImageView imageView) {
                this.imageView = imageView;
                this.holder = holder;
                this.holder.withRetry(this);
            }

**Comment by lxn1445663013** [comment]
我是克隆代码自己运行的，刚刚我下载Dome试了也是报错，对比GridView中的代码是有convertView = holder.getWrapper();这段代码的

**Comment by luckybilly** [comment]
下载demo apk运行报了什么错？什么设备？能不能贴一下日志

**Comment by lxn1445663013** [comment]
运行设备是夜神模拟器，下面是日志
04-11 11:50:30.502 2524-2524/com.billy.android.loadingstatusview E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.billy.android.loadingstatusview, PID: 2524
    java.lang.ClassCastException: android.view.ViewGroup$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
        at android.widget.GridView.onMeasure(GridView.java:1046)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:327)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
        at android.view.View.measure(View.java:16497)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1940)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1137)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1319)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1024)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5694)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
        at android.view.Choreographer.doFrame(Choreographer.java:544)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by luckybilly** [comment]
我用多台手机和genymotion模拟器都试了一下，工作正常，这就尴尬了...
要不你在手机上再试试？
从原理上来讲这个Exception应该是在没有使用holder.getWrapper()的情况下才会出现。但demo是不会有这个问题的。

**Comment by lxn1445663013** [comment]
还真是在夜神模拟器上面就是不行，手机上面是没什么问题的，这确实比较尴尬啊
